export async function mountLogin(app){
 const api=async body=>{const r=await fetch('/.netlify/functions/auth',body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{});const data=await r.json();if(!r.ok)throw Error(data.error||'Login failed');return data;};
 app.innerHTML='<section class="about-page"><div class="catalogue-heading"><h1>Wallet login</h1></div><div class="card markdown-body"><p id="login-status" role="status">Checking your session…</p><div id="login-controls"></div></div></section>';
 const status=app.querySelector('#login-status'),controls=app.querySelector('#login-controls');
 try{const session=await api();if(session.user){status.textContent='Signed in · '+session.user.fingerprint.slice(0,16);controls.innerHTML='<h2>My repositories</h2><div id="my-repositories"></div><p>Login identifies your wallet. Repository publishing still uses the local CLI and deployment workflow.</p><button id="logout">Sign out</button>';const catalogue=await (await fetch('catalogue.json')).json();const own=catalogue.repositories.filter(x=>x.repositoryId.startsWith(session.user.fingerprint+'/'));const target=controls.querySelector('#my-repositories');if(!own.length)target.textContent='No repositories for this identity in the published catalogue.';for(const repo of own){const a=document.createElement('a');a.href='#repo/'+encodeURIComponent(repo.repositoryId)+'/code';a.textContent=repo.owner+'/'+repo.name;target.append(a,document.createElement('br'));}controls.querySelector('#logout').onclick=async()=>{try{await api({action:'logout'});await mountLogin(app);}catch(e){status.textContent=e.message;}};return;}
 status.textContent='Sign a one-time challenge locally. Your private key stays on your machine.';
 controls.innerHTML='<button id="challenge">Download login challenge</button><p>Keep this browser tab open. Run the command below with your existing local QPository identity, then paste the returned public proof.</p><pre>qpo login-sign /path/to/qpository-login.json</pre><label for="login-proof">Public login proof (JSON)</label><textarea id="login-proof" rows="5" style="width:100%;background:var(--bg);color:var(--text);border:1px solid var(--border)" placeholder="Paste the output of qpo login-sign here"></textarea><button id="login-submit" disabled>Sign in</button><p>No wallet yet? <a href="#start">Get started</a>. This proof expires after five minutes and is valid only in this browser.</p>';
 controls.querySelector('#challenge').onclick=async()=>{try{const c=await api({action:'challenge'});const url=URL.createObjectURL(new Blob([JSON.stringify(c)],{type:'application/json'}));const link=document.createElement('a');link.href=url;link.download='qpository-login.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);controls.querySelector('#login-submit').disabled=false;status.textContent='Challenge ready. Sign it locally within five minutes.';}catch(e){status.textContent=e.message;}};
 controls.querySelector('#login-submit').onclick=async()=>{try{const proof=JSON.parse(controls.querySelector('#login-proof').value);if(Object.keys(proof).some(k=>!['id','publicKey','signature'].includes(k)))throw Error('Paste only the public login-sign output. Never paste a wallet or private key.');await api({...proof,action:'verify'});await mountLogin(app);}catch(e){status.textContent=e.message;}};
 }catch(e){status.textContent=e.message;}
}
